### ISSUE TITLE
grunt-spritesmith 버전 업 대응

### ISSUE THREAD

**Issue by uyeong** [WebFrontEnd/grunt-init-markup#18]
현재 spritesmith 버전은 3.6.0 입니다. 이를 최신 버전으로 반영해야합니다.
이 글을 작성하는 시점에 최신 버전은 4.3입니다. 4.3에서는 템플릿 엔진을 mustache에서 handlebars 변경([참고](https://github.com/Ensighten/grunt-spritesmith/commit/17b2b4aa420c4a08a9cfafd050e7cbe634ab23b7)) 했으므로 sprites.mustache 템플릿 역시 새로 작성하여 대응해야합니다.(4.3 이하 버전에선 mustache를 사용할 수 있습니다.)

**Comment by hyunchulkwak** [comment]
패기롭게(...) mustache require를 부탁합니다.

**Comment by uyeong** [comment]
완료!
